"""Domain models for code modifications.

This module defines the structures used by the LLM to propose exact,
platform-agnostic string replacements to fix failing code.
"""

from pydantic import BaseModel, Field, field_validator


class SearchReplacePatch(BaseModel):
    """An exact string replacement operation for a specific file.

    Attributes:
        file_path (str): The exact relative path to the target file.
        search_block (str): The exact code to replace, matching byte-for-byte.
        replace_block (str): The new code to insert.
    """

    file_path: str = Field(description="The exact relative path to the file.")
    search_block: str = Field(
        description="The exact block of code to be replaced. Must match the file byte-for-byte, including indentation."
    )
    replace_block: str = Field(
        description="The new block of code to insert in its place."
    )


class PatchRecommendation(BaseModel):
    """A comprehensive fix proposal generated by the AI.

    Attributes:
        root_cause (str): Detailed explanation of why the failure occurred.
        proposed_solution (str): Explanation of the code modifications.
        patches (list[SearchReplacePatch]): Exact search/replace blocks to apply.
        unified_diff (str): A visual diff string strictly for human review.
    """

    root_cause: str = Field(
        description="Detailed explanation of why the failure occurred."
    )
    proposed_solution: str = Field(description="Explanation of the code modifications.")
    patches: list[SearchReplacePatch] = Field(
        description="List of exact search/replace blocks to apply to the files."
    )
    unified_diff: str = Field(
        description="A visual unified diff patch for the human reviewer. Must be a single string."
    )

    @field_validator("unified_diff", mode="before")
    @classmethod
    def assemble_diff(cls, value: str | list[str]) -> str:
        """Fixes LLM arrays into proper strings.

        Args:
            value (str | list[str]): The raw diff output from the LLM.

        Returns:
            str: A guaranteed single string representation of the diff.
        """
        if isinstance(value, list):
            return "\n".join(value)
        return value
