"""Filesystem layer for code modification and patch persistence.

This module provides the PatchManager class, which executes precision
search-and-replace operations on source code and saves visual unified
diffs for human review.
"""

from pathlib import Path

from src.utils.diff import normalize_line_endings
from src.utils.logger import get_logger

logger = get_logger(__name__)


class PatchManager:
    """Manages source code modification and patch history.

    Attributes:
        workspace (Path): The target codebase root directory.
        patches_dir (Path): The directory to store visual diff history.
    """

    def __init__(self, workspace: Path, patches_dir: Path) -> None:
        """Initializes the PatchManager.

        Args:
            workspace (Path): The root directory of the codebase to modify.
            patches_dir (Path): The directory to store .diff files.
        """
        self.workspace = workspace
        self.patches_dir = patches_dir
        self.patches_dir.mkdir(parents=True, exist_ok=True)

    def save_unified_diff(self, retry_number: int, diff_content: str) -> None:
        """Saves a visual unified diff to disk purely for human review.

        Args:
            retry_number (int): The current retry loop iteration.
            diff_content (str): The unified diff string generated by the LLM.
        """
        patch_file = self.patches_dir / f"retry-{retry_number}.diff"
        try:
            patch_file.write_text(diff_content, encoding="utf-8")
            logger.debug(f"Unified diff saved to {patch_file}")
        except Exception as e:
            logger.error(f"Failed to save patch file {patch_file}: {e}")

    def apply_search_replace(
        self, relative_path: str, search_block: str, replace_block: str
    ) -> None:
        """Applies an exact string replacement to a target file.

        Automatically neutralizes OS-level line ending conflicts (CRLF vs LF)
        to ensure byte-perfect search matches.

        Args:
            relative_path (str): The file path relative to the workspace.
            search_block (str): The exact code snippet to find.
            replace_block (str): The exact code snippet to insert.

        Raises:
            FileNotFoundError: If the target source file does not exist.
            RuntimeError: If the search block cannot be found in the file.
        """
        abs_path = self.workspace / relative_path

        if not abs_path.exists():
            raise FileNotFoundError(f"Target file does not exist: {abs_path}")

        # Read and normalize the entire source file
        content = abs_path.read_text(encoding="utf-8")
        content_normalized = normalize_line_endings(content)

        # Normalize the LLM's requested blocks
        search_normalized = normalize_line_endings(search_block)
        replace_normalized = normalize_line_endings(replace_block)

        if search_normalized not in content_normalized:
            logger.debug(f"Target search block:\n{search_normalized}")
            raise RuntimeError(
                f"Could not find the target search block in {relative_path}. "
                "The LLM may have hallucinated the existing code or indentation."
            )

        # Apply the modification
        new_content = content_normalized.replace(search_normalized, replace_normalized)

        # Write back to disk enforcing Unix line endings
        with open(abs_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(new_content)

        logger.info(f"Successfully applied search/replace patch to {relative_path}")
