"""Utility module for string manipulation and LLM output sanitization.

This module provides pure functions to normalize cross-platform line endings,
strip markdown formatting hallucinated by language models, and prepare code
blocks for exact string replacement operations.
"""

import re


def normalize_line_endings(text: str) -> str:
    """Normalizes cross-platform line endings to standard Unix LF.

    This function safely converts Windows (CRLF) and legacy Mac (CR) line
    endings into standard Linux/Unix (LF) newlines. This is critical for
    ensuring byte-for-byte matches during string replacement operations,
    especially when bridging WSL and Windows filesystems.

    Args:
        text (str): The raw string containing potentially mixed line endings.

    Returns:
        str: The normalized string containing only '\\n' line endings.
    """
    # Replace CRLF (\r\n) first, then standalone CR (\r)
    return text.replace("\r\n", "\n").replace("\r", "\n")


def strip_markdown_blocks(text: str) -> str:
    """Removes markdown code fences from a string.

    Large Language Models often wrap code snippets in markdown code blocks
    (e.g., ```python ... ``` or just ``` ... ```) even when explicitly
    instructed to return raw text. This function safely strips the bounding
    fences while preserving the internal indentation and content.

    Args:
        text (str): The raw string output from an LLM.

    Returns:
        str: The clean code block without markdown fences.
    """
    text = text.strip()

    # Regex to match ```<language>\n  ...  \n``` and extract the inner content
    # re.DOTALL ensures the '.' matches newlines.
    pattern = r"^```[a-zA-Z]*\n(.*?)```$"

    match = re.search(pattern, text, flags=re.DOTALL | re.MULTILINE)
    if match:
        return match.group(1).strip("\n")

    return text


def sanitize_patch_block(block: str) -> str:
    """Prepares an LLM-generated code block for exact search/replace operations.

    This is a convenience pipeline function that sequentially normalizes line
    endings and strips any hallucinatory markdown formatting, returning a
    production-ready string.

    Args:
        block (str): The raw code block (either search or replace block)
            generated by the language model.

    Returns:
        str: The fully sanitized and normalized code block.
    """
    normalized = normalize_line_endings(block)
    stripped = strip_markdown_blocks(normalized)

    # We do not strip trailing/leading spaces here, as indentation
    # must be preserved byte-for-byte for the replacement to work.
    return stripped
